# Generated by Django 4.2 on 2023-11-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='adverties_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('location_City', models.CharField(max_length=20)),
                ('contact_Number', models.IntegerField(default=0)),
                ('product_Image', models.ImageField(default=0, upload_to='adverties/image')),
            ],
        ),
    ]
