# Generated by Django 4.2 on 2024-09-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
