# Generated by Django 4.2 on 2024-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
