# Generated by Django 4.2 on 2024-09-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_laptop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
