# Generated by Django 4.2 on 2024-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_delete_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='free_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_Name', models.CharField(max_length=100)),
                ('business_Type', models.CharField(max_length=20)),
                ('location_City', models.CharField(max_length=20)),
                ('contact_Number', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
