# Generated by Django 4.2 on 2024-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_free_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_listing',
            name='organization_Name',
            field=models.CharField(max_length=20),
        ),
    ]
