# Generated by Django 4.2 on 2024-09-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_free_listing_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_listing',
            name='organization_Name',
        ),
    ]
