# Generated by Django 4.2 on 2024-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_free_listing_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_listing',
            name='organization_Name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
