# Generated by Django 4.2 on 2024-09-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_free_listing_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_listing',
            name='business_Type',
            field=models.CharField(default='Default Type', max_length=20),
        ),
        migrations.AlterField(
            model_name='free_listing',
            name='organization_Name',
            field=models.CharField(max_length=20),
        ),
    ]
