# Generated by Django 4.2 on 2024-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_business_delete_free_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
