# Generated by Django 4.2 on 2024-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_alter_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.IntegerField(choices=[(7, 'Restaurant'), (12, 'Doctor'), (15, 'Groceries'), (17, 'Electrician'), (18, 'Contractor')]),
        ),
    ]
